#!/bin/sh
#
# tensix operating system project
# Copyright (C) 2003 Sven Klose <pixel@copei.de>
#
# $License$

chkargs $1

subdir mem "memory management"
subdir proc "process management"
subdir io "I/O system"
subdir boot "boot code"
subdir machdep "machdep interface"
