#!/bin/sh
#
# tensix operating system project
# Copyright (C) 2004 Sven Klose <pixel@copei.de>
#
# $License$

chkargs $1

case $MODE in
build)
    compile uip.c uipobj.c
    ;;

clean)
    clean
    ;;
esac
