#!/bin/sh
#
# tensix operating system project
# Copyright (C) 2002, 2003 Sven Klose <pixel@copei.de>
#
# $License$

chkargs $1

case $ARCH in
unix)
    subdir con "console (ASCII/ISO 646)"
    ;;

cpc)
#    subdir con "console (ASCII/ISO 646)"
    ;;

*)
    echo "Missing ARCH."
    exit -1
    ;;
esac
