#!/bin/sh
#
# tensix operating system project
# Copyright (C) 2002, 2003, 2004, 2005 Sven Klose <pixel@copei.de>
#
# $License$

chkargs $1
subdir dfs "directory file system"
subdir holographicfs "holographic file system"
subdir nixfs "nix file store"
subdir memfs "memory file system"
subdir wrapfs "wrapper file system"
